import { StyleSheet } from 'react-native'
import { COLORS } from './color'

export const TYPOGRAPHY = StyleSheet.create({
  heading1: {
    fontSize: 48,
    lineHeight: 52,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  heading2: {
    fontSize: 40,
    lineHeight: 44,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  heading3: {
    fontSize: 32,
    lineHeight: 36,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  heading4: {
    fontSize: 24,
    lineHeight: 28,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  heading5: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  heading6: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  body18Bold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body18SemiBold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body18Medium: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body18Normal: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body16Bold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body16SemiBold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body16Medium: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body16Normal: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body14Bold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body14SemiBold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body14Medium: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body14Normal: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.2,
    color: COLORS.gray90,
  },
  body12Bold: {
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  body12SemiBold: {
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-SemiBold',
    color: COLORS.gray90,
  },
  body12Medium: {
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Medium',
    color: COLORS.gray90,
  },
  body12Normal: {
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Regular',
    color: COLORS.gray90,
  },
  body10Bold: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Bold',
    color: COLORS.gray90,
  },
  body10SemiBold: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-SemiBold',
    color: COLORS.gray90,
  },
  body10Medium: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Medium',
    color: COLORS.gray90,
  },
  body10Normal: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    fontFamily: 'Nunito-Regular',
    color: COLORS.gray90,
  },
})
